CREATE TABLE IF NOT EXISTS users(
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS skills(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS languages(
	id BIGSERIAL PRIMARY KEY,
	user_id UUID NOT NULL,
	name VARCHAR(100) NOT NULL,
	color_hex VARCHAR(7) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS study_sessions(
	id BIGSERIAL PRIMARY KEY,
	user_id UUID NOT NULL,
	language_id BIGINT NOT NULL,
	skill_id BIGINT NOT NULL,
	date DATE NOT NULL,
	duration_minutes INT NOT NULL,
	notes TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (language_id) REFERENCES languages(id) ON DELETE CASCADE,
	FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS weekly_goals(
	id BIGSERIAL PRIMARY KEY,
	user_id UUID NOT NULL,
	language_id BIGINT NOT NULL,
	target_minutes INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
	FOREIGN KEY (language_id) REFERENCES languages(id) ON DELETE CASCADE,
	CONSTRAINT uq_user_language UNIQUE (user_id, language_id)
);

